name: get-diff-between-branches-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: [pull_request]

jobs:
  get-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all branches
        run: git fetch --all
      - name: Compare main vs dev and save diff
        run: git diff origin/main origin/dev -- . ':(exclude).github/workflows/' > differences.json
        
      - name: Upload differences.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: differences
          path: differences.json
